Fix error sending emails with servers that have a long hostname
The generated message id header was returning for hosts with a very long
name:

ValueError: Malformed Message-Id header

We actually do not need to send it because it will be autogenerated by
lower level code.